### ISSUE TITLE
Allow admins to see which users did which work

### ISSUE THREAD

**Issue by zjmiller** [oughtinc/mosaic#501] opened 2019-05-07 18:34 UTC

**Comment by zjmiller** [comment] 2019-05-07 22:21
> If we also implement “create a log for the user to explain why they’re doing what they’re doing every time they do a round of work”, it may be enough just to allow admins to see which users touched a given workspace.

**Comment by brachbach** [comment] 2019-07-17 18:56
sort of duplicate of #606, sort of already implemented

**Closed** 2019-07-17 18:56 UTC
Labels: Exp 4/19
