### ISSUE TITLE
Validation error when creating nested lists

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#221] opened 2018-10-23 22:39 UTC
Sometimes, when I create nested lists like this one:

<img width="552" alt="screen shot 2018-10-23 at 3 35 24 pm" src="https://user-images.githubusercontent.com/382515/47394973-b358f900-d6d9-11e8-8295-39679068be5d.png">

I get validation errors like this one:

<img width="626" alt="screen shot 2018-10-23 at 3 37 43 pm" src="https://user-images.githubusercontent.com/382515/47394979-bb189d80-d6d9-11e8-8c0a-fa28c0613475.png">

**Comment by stuhlmueller** [comment] 2018-10-23 22:52
Related: I think the app sometimes fails to properly create the entire set of nested pointers. I just had a case where I referred to a large list using $1 in the answer, but the next time I got back to the workspace, the pointer in the answer had turned to n/a and the outer-most [ ] in the scratchpad hadn't been turned into an export and instead remained as plain-text square brackets.

**Comment by zjmiller** [comment] 2018-10-25 18:15
Was able to duplicate validation error:

Here is Postgres tells us is going on:
```
ERROR:  duplicate key value violates unique constraint "Pointers_pkey"
DETAIL:  Key (id)=(87f69da0-d880-11e8-89a3-f3e3e73d8d6e) already exists.
STATEMENT:  INSERT INTO "Pointers" ("id","createdAtEventId","updatedAtEventId","createdAt","updatedAt","sourceBlockId") VALUES ('87f69da0-d880-11e8-89a3-f3e3e73d8d6e',168,168,'2018-10-25 18:05:18.806 +00:00','2018-10-25 18:05:18.806 +00:00','837b0ff4-53d3-486d-90fa-e3f1c2203d79') RETURNING *;
```

I'm 99% sure this is a race condition caused by the following: When a block is updated, there is a "after save" callback that ensures that all of the block's pointers are in the database. If some pointers aren't yet in the database (i.e., they're new), then they are created. When creating so many pointers in such short succession, with each act of pointer creation instigating a block update, there's a chance things get out of order and that the pointer actually get created in between (1) looking to see whether a pointer exists and (2) creating the pointer.

This shouldn't cause any larger problem though, because it just means the pointer isn't created twice (which is what we want).

**Comment by zjmiller** [comment] 2018-11-01 15:47
Ok so on the current preview branch (v0.3) this is resolved by not having the editor save to the database after every pointer creation. Now, saves occur only after the autosave interval, or when the editor unmounts.

**Closed** 2019-03-29 20:33 UTC
Labels: high-priority, in-preview-v0.3
